# Generated by Django 5.0.7 on 2024-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='education',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
