# Generated by Django 5.0.7 on 2024-08-09 10:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('education', models.CharField(max_length=200)),
                ('education_type', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('perents_name', models.CharField(blank=True, max_length=100, null=True)),
                ('perents_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('enrollment_status', models.CharField(max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
