# Generated by Django 5.0.7 on 2024-08-21 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classroom', '0002_classroom_education'),
        ('Course', '0002_rename_name_course_course_name'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Present', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.classroom')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
