# Generated by Django 5.0.7 on 2024-08-08 10:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('otp', models.CharField(max_length=50)),
                ('expiration_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
